### PR TITLE
Removed ReservationWaitTime

### LINKED ISSUE #180: PATCH call to reservation wipes out movingAverage
When the consumer makes a PATCH call to update the resolution of a call, it's clearing out the movingAverageWaitTime field on that Reservation. This is causing future calculations of the movingAverageWaitTime to be incorrect.

### PR DESCRIPTION
**Pull request by egracer**
Fixes #180.

The Reservation class was overwriting the waitTimeMovingAverage field
stored by the ReservationWaitTime class when saving the document to MongoDB. Moving the field into Reservation stops it from being overwritten on subsequent changes to the Reservation.

- [X] Tests pass
- [X] Appropriate changes to README are included in PR
- [X] Feature has been fleshed out in design document

### CODE REVIEW

File: callmeback/backend/src/main/java/org/google/callmeback/api/QueueingRepository.java [hunk 1]
```diff
@@ -108,11 +108,11 @@ public OptionalDouble getMovingAverage() {
...
 
-    AggregationResults<ReservationWaitTime> results =
-        mongoTemplate.aggregate(agg, "reservation", ReservationWaitTime.class);
+    AggregationResults<Reservation> results =
+        mongoTemplate.aggregate(agg, "reservation", Reservation.class);
 
-    List<ReservationWaitTime> resultList = results.getMappedResults();
-    ReservationWaitTime previousMovingAverage = resultList.stream().findFirst().orElse(null);
+    List<Reservation> resultList = results.getMappedResults();
+    Reservation previousMovingAverage = resultList.stream().findFirst().orElse(null);
```
Comment (kebrahim) [inline callmeback/backend/src/main/java/org/google/callmeback/api/QueueingRepository.java:115]: s/previousMovingAverage/lastConnectedReservation

File: callmeback/backend/src/main/java/org/google/callmeback/api/Reservation.java [hunk 2]
```diff
@@ -56,6 +56,16 @@
...
 
+  /**
+   * The exponential moving average, in milliseconds, representing the average wait time based on
+   * the previous moving average and the time that it took for this Reservation to be connected with
+   * an agent.
+   *
+   * <p>Therefore, the moving average stored on a reservation document does *not* represent the
+   * amount of time that the reservation waited before being connected with an agent.
+   */
+  public double waitTimeMovingAverage;
```
Comment (kebrahim) [inline callmeback/backend/src/main/java/org/google/callmeback/api/Reservation.java:67]: did you want to leave a comment that this isn't the ideal place to store this?

Comment (mscharfstein) [reply callmeback/backend/src/main/java/org/google/callmeback/api/Reservation.java:67]: +1

**Comment by mscharfstein** [comment]
have you checked that this actually fixes the problem by running the consumer script?

File: callmeback/backend/src/main/java/org/google/callmeback/api/QueueingRepository.java (hunk 1 above)
Comment (egracer) [reply callmeback/backend/src/main/java/org/google/callmeback/api/QueueingRepository.java:115]: I don't think `lastConnectedReservation` is quite right, since this field stores the moving average of the wait time accumulated over the past `n` reservations, where `n` is a number set in the application configuration. 

This field literally does store the moving average calculated for all events prior to this one. Is there a clearer way to capture that in the name?

Comment (egracer) [reply callmeback/backend/src/main/java/org/google/callmeback/api/QueueingRepository.java:115]: Done

**Comment by egracer** [comment]
I have and it does!
