### PR TITLE
mark the reservation object as updated when the window is calculated so that w…

### LINKED ISSUE #157: FE is displaying incorrect wait times
wait time has gone from:
- a few seconds - 10 minutes
- 1 min - 9 min
- 2 min - 8 min
- 3 min - 7 min

### PR DESCRIPTION
**Pull request by mscharfstein**
…the updated version is returned

Fixes #157 

- [x] Tests pass
- [x] Appropriate changes to README are included in PR
- [x] Feature has been fleshed out in design document

### CODE REVIEW

File: callmeback/backend/src/main/java/org/google/callmeback/api/CustomizedReservationRepository.java [hunk 1]
```diff
@@ -45,6 +48,7 @@
   public Optional<T> findById(ID id) {
     Reservation reservation = mongoTemplate.findById(id, Reservation.class);
     reservation.window = getWindow(reservation.requestDate);
+    auditingHandler.markModified(reservation);
```
Comment (kebrahim) [inline callmeback/backend/src/main/java/org/google/callmeback/api/CustomizedReservationRepository.java:51]: please add a comment why this is necessary

Comment (mscharfstein) [reply callmeback/backend/src/main/java/org/google/callmeback/api/CustomizedReservationRepository.java:53]: done
